# Generated by Django 3.2.3 on 2021-06-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0002_auto_20210601_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tentativa',
            name='pontuacao_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
