# Generated by Django 3.2.3 on 2021-06-01 15:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0007_auto_20210601_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='inicio',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tentativa',
            name='entrega',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
