# Generated by Django 3.2.3 on 2021-06-01 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0008_auto_20210601_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizz',
            name='inicio',
        ),
    ]
