# Generated by Django 3.2.3 on 2021-05-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15)),
                ('apelido', models.CharField(max_length=15)),
                ('telefone', models.TextField(max_length=9)),
                ('email', models.TextField(max_length=40)),
                ('mensagem', models.TextField(max_length=500)),
            ],
        ),
    ]
