# Generated by Django 3.2.3 on 2021-05-31 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pw', '0002_auto_20210531_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='enviado',
            new_name='criado',
        ),
    ]
