# Generated by Django 3.2.3 on 2021-06-01 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pw', '0003_rename_enviado_contacto_criado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
