# Generated by Django 3.2.3 on 2021-06-01 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pw', '0004_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='amplitude',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comentario',
            name='clareza',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comentario',
            name='logica',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comentario',
            name='originalidade',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comentario',
            name='precisao',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comentario',
            name='profundidade',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comentario',
            name='rigor',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comentario',
            name='significancia',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
