# Generated by Django 3.2.4 on 2021-06-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pw', '0005_auto_20210601_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='amplitude',
            field=models.IntegerField(choices=[(1, 'PÉSSIMO'), (2, 'MAU'), (3, 'BOM'), (4, 'MUITO BOM'), (5, 'EXCELENT')], default=5),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='clareza',
            field=models.IntegerField(choices=[(1, 'PÉSSIMO'), (2, 'MAU'), (3, 'BOM'), (4, 'MUITO BOM'), (5, 'EXCELENT')], default=5),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='logica',
            field=models.IntegerField(choices=[(1, 'PÉSSIMO'), (2, 'MAU'), (3, 'BOM'), (4, 'MUITO BOM'), (5, 'EXCELENT')], default=5),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='originalidade',
            field=models.IntegerField(choices=[(1, 'PÉSSIMO'), (2, 'MAU'), (3, 'BOM'), (4, 'MUITO BOM'), (5, 'EXCELENT')], default=5),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='precisao',
            field=models.IntegerField(choices=[(1, 'PÉSSIMO'), (2, 'MAU'), (3, 'BOM'), (4, 'MUITO BOM'), (5, 'EXCELENT')], default=5),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='profundidade',
            field=models.IntegerField(choices=[(1, 'PÉSSIMO'), (2, 'MAU'), (3, 'BOM'), (4, 'MUITO BOM'), (5, 'EXCELENT')], default=5),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='rigor',
            field=models.IntegerField(choices=[(1, 'PÉSSIMO'), (2, 'MAU'), (3, 'BOM'), (4, 'MUITO BOM'), (5, 'EXCELENT')], default=5),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='significancia',
            field=models.IntegerField(choices=[(1, 'PÉSSIMO'), (2, 'MAU'), (3, 'BOM'), (4, 'MUITO BOM'), (5, 'EXCELENT')], default=5),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='email',
            field=models.EmailField(max_length=40),
        ),
    ]
