# Generated by Django 3.2.4 on 2021-06-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pw', '0007_auto_20210604_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clareza', models.IntegerField(choices=[(1, 'PÉSSIMO'), (2, 'MAU'), (3, 'BOM'), (4, 'MUITO BOM'), (5, 'EXCELENTE')], default=3)),
                ('rigor', models.IntegerField(choices=[(1, 'PÉSSIMO'), (2, 'MAU'), (3, 'BOM'), (4, 'MUITO BOM'), (5, 'EXCELENTE')], default=3)),
                ('precisao', models.IntegerField(choices=[(1, 'PÉSSIMO'), (2, 'MAU'), (3, 'BOM'), (4, 'MUITO BOM'), (5, 'EXCELENTE')], default=3)),
                ('profundidade', models.IntegerField(choices=[(1, 'PÉSSIMO'), (2, 'MAU'), (3, 'BOM'), (4, 'MUITO BOM'), (5, 'EXCELENTE')], default=3)),
                ('amplitude', models.IntegerField(choices=[(1, 'PÉSSIMO'), (2, 'MAU'), (3, 'BOM'), (4, 'MUITO BOM'), (5, 'EXCELENTE')], default=3)),
                ('logica', models.IntegerField(choices=[(1, 'PÉSSIMO'), (2, 'MAU'), (3, 'BOM'), (4, 'MUITO BOM'), (5, 'EXCELENTE')], default=3)),
                ('significancia', models.IntegerField(choices=[(1, 'PÉSSIMO'), (2, 'MAU'), (3, 'BOM'), (4, 'MUITO BOM'), (5, 'EXCELENTE')], default=3)),
                ('originalidade', models.IntegerField(choices=[(1, 'PÉSSIMO'), (2, 'MAU'), (3, 'BOM'), (4, 'MUITO BOM'), (5, 'EXCELENTE')], default=3)),
            ],
        ),
        migrations.DeleteModel(
            name='Comentarios_Avaliacao',
        ),
        migrations.DeleteModel(
            name='Comentarios_Categorias',
        ),
        migrations.DeleteModel(
            name='Comentarios_Notas',
        ),
    ]
